name: Deploy Vite + React App to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cada push a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # 1️⃣ Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the project
      - name: Build
        run: npm run build

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      # 6️⃣ Optional: Configure the environment URL (automático)
      - name: Set output URL
        run: echo "Your app should be available shortly via GitHub Pages"
